services:
  - type: web
    name: fireworks-inventory
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_YOUTUBE_API_KEY
        value: AIzaSyD457DJOvlY9-kfIMIGY-DsUSc-NTl62JA
